version: "3.3"
services:
  db:
    image: postgres:alpine
    restart: "always"
    environment: 
      POSTGRES_PASSWORD: 123
    ports: 
      - "5432:5432"
  plant-app-backend:
    image: octavius2929/plant_app_backend 
    restart: "always"
    ports: 
      - "80:80"
    depends_on: 
      - "db"
    environment: 
      PORT: 80
      JWT_SECRECT: 'lapampara'
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: root
      ADMIN_EMAIL: admin@gmail.com
      JWT_SECRECT: mysecret
      POSTGRES_HOST: "db"
      POSTGRES_PORT: '5432'
      POSTGRES_PASSWORD: '123'
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_DATABASE: 'plant_pro'
      POSTGRES_URI: 'db:5432'
      NODE_ENV: 'pro'