version: "3.3"
services:
  db:
    image: postgres:alpine
    restart: "always"
    environment: 
      POSTGRES_PASSWORD: 123
    ports: 
      - "5432:5432"
  plant-app-backend:
    build: .
    restart: "always"
    ports: 
      - "8080:8080"
    depends_on: 
      - "db"
    environment: 
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: root
      ADMIN_EMAIL: admin@gmail.com
      JWT_SECRECT: mysecret
      POSTGRES_HOST: "db"
      POSTGRES_URI: 'db:5432'
      NODE_ENV: 'dev'